export const IMAGE_INTEREST_OBJECT_CLASS_ID = {
    ALL_CLASSES: Symbol('allClasses'),
    // FOOD: Symbol('food'),
    // ANIMAL: Symbol('animal'),
    // ELECTRONIC: Symbol('electronic'),
    // KITCHEN: Symbol('kitchen'),
    // FURNITURE: Symbol('furniture'),
    // SPORTS: Symbol('sports'),
    // VEHICLE: Symbol('vehicle'),
    // TEXTILE: Symbol('textile'),
    // PLANT: Symbol('plant'),
    // WATER: Symbol('water'),
    // BUILDING: Symbol('builing'),
    FOOD: 'food',
    ANIMAL: 'animal',
    ELECTRONIC: 'electronic',
    KITCHEN: 'kitchen',
    FURNITURE: 'furniture',
    SPORTS: 'sports',
    VEHICLE: 'vehicle',
    TEXTILE: 'textile',
    PLANT: 'plant',
    WATER: 'water',
    BUILDING: 'builing',
}

export const IMAGE_INTEREST_OBJECT_CLASS_ID_TO_TEXT = {
    [IMAGE_INTEREST_OBJECT_CLASS_ID.ALL_CLASSES]: '全部',
    [IMAGE_INTEREST_OBJECT_CLASS_ID.FOOD]: '食品',
    [IMAGE_INTEREST_OBJECT_CLASS_ID.ANIMAL]: '动物',
    [IMAGE_INTEREST_OBJECT_CLASS_ID.ELECTRONIC]: '电子产品',
    [IMAGE_INTEREST_OBJECT_CLASS_ID.KITCHEN]: '厨房用品',
    [IMAGE_INTEREST_OBJECT_CLASS_ID.FURNITURE]: '家具',
    [IMAGE_INTEREST_OBJECT_CLASS_ID.SPORTS]: '运动',
    [IMAGE_INTEREST_OBJECT_CLASS_ID.VEHICLE]: '交通工具',
    [IMAGE_INTEREST_OBJECT_CLASS_ID.TEXTILE]: '纺织品',
    [IMAGE_INTEREST_OBJECT_CLASS_ID.PLANT]: '植物',
    [IMAGE_INTEREST_OBJECT_CLASS_ID.WATER]: '水',
    [IMAGE_INTEREST_OBJECT_CLASS_ID.BUILDING]: '建筑物'
}